options:
  machineType: E2_MEDIUM # 1 vCPU
  logging: CLOUD_LOGGING_ONLY

steps:

- name: 'gcr.io/cloud-builders/docker'
  id: Build Caddy
  args:
  - 'build'
  - '-t'
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/public/caddy:$TAG_NAME'
  - '.'


- name: 'gcr.io/cloud-builders/docker'
  id: Push Caddy to Container registry
  args:
  - 'push'
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/public/caddy:$TAG_NAME'
